from .alternativa_renda import AlternativaRenda
from .area_pesca import AreaPesca
from .arte_pesca import ArtePesca
from .associacao import Associacao
from .atividade_anterior import AtividadeAnterior
from .beneficio_colonia import BeneficioColonia
from .colonia import Colonia
from .companhia import Companhia
from .comprador_pescado import CompradorPescado
from .comunidade import Comunidade
from .curso_beneficiamento import CursoBeneficiamento
from .dependente import Dependente
from .destino_pescado import DestinoPescado
from .destino_sobras import DestinoSobras
from .dificuldade_area import DificuldadeArea
from .dificuldade_pagamento import DificuldadePagamento
from .emissor_rgp import EmissorRgp
from .endereco import Endereco
from .especie_capturada import EspecieCapturadaDoPescador
from .estado_civil import EstadoCivil
from .fonte_renda_durante_defeso import FonteRendaDuranteDefeso
from .fornecedor_insumos import FornecedorInsumos
from .frequencia_consumo import FrequenciaConsumo
from .frequencia_pesca import FrequenciaPesca
from .gostaria_fazer_nao_fosse_pescador import GostariaFazerNaoFossePescador
from .habilidade_outra_area import HabilidadeOutraArea
from .horario_pesca import HorarioPesca
from .insumo_do_pescador import InsumoDoPescador
from .item_estrutura_residencial import ItemEstruturaResidencial
from .local_tratamento import LocalTratamento
from .motivacao_pesca import MotivacaoPesca
from .motivo_filho_seguir_profissao import MotivoFilhoSeguirProfissao
from .motivo_nao_participou_oficinas import MotivoNaoParticipouOficinas
from .municipio import Municipio
from .opiniao_oficinas import OpiniaoOficinas
from .parente_pescador import ParentePescador
from .pescador_especialista import PescadorEspecialista
from .pescador import Pescador
from .porto import Porto
from .programa_social import ProgramaSocial
from .projeto import Projeto
from .relacao_companhia import RelacaoCompanhia
from .relacao_parentesco import RelacaoParentesco
from .relacao_tutor import RelacaoTutor
from .renda import Renda
from .renda_durante_defeso import RendaDuranteDefeso
from .telefone import Telefone
from .tipo_insumo import TipoInsumo
from .tipo_residencia import TipoResidencia
from .tipo_seguro_defeso import TipoSeguroDefeso
from .transporte import Transporte
from .unidade_beneficiamento import UnidadeBeneficiamento
