from .pescador import *
from .pescador_especialista import *
from .area_pesca import *
from .arte_pesca import *
from .comunidade import *
from .associacao import *
from .municipio import *
from .endereco import *
from .colonia import *
from .dependente import *
from .telefone import *
